In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier  
from sklearn.ensemble import RandomForestClassifier

from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression

from sklearn.preprocessing import StandardScaler
from sklearn import model_selection
from scipy.stats import zscore

from sklearn import metrics
from sklearn.model_selection import GridSearchCV

import warnings
warnings.filterwarnings('ignore')

from IPython.display import Image
from sklearn import tree
from os import system

C:\Users\Gaurav\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [3]:
df = pd.read_csv('wine.xls', names = ['Class','Alcohol', 'Malic_Acid','Ash','AlcaofAsh', 'Mg','Tot_phenol','Flavanoid','NonFlaPh','Proanthocyanins','Color_Intensity','Hue','OD280/OD315 of diluted wines','Proline'])
df.head()

Class  Alcohol  Malic_Acid   Ash  AlcaofAsh   Mg  Tot_phenol  Flavanoid  \
0      1    14.23        1.71  2.43       15.6  127        2.80       3.06   
1      1    13.20        1.78  2.14       11.2  100        2.65       2.76   
2      1    13.16        2.36  2.67       18.6  101        2.80       3.24   
3      1    14.37        1.95  2.50       16.8  113        3.85       3.49   
4      1    13.24        2.59  2.87       21.0  118        2.80       2.69   

   NonFlaPh  Proanthocyanins  Color_Intensity   Hue  \
0      0.28             2.29             5.64  1.04   
1      0.26             1.28             4.38  1.05   
2      0.30             2.81             5.68  1.03   
3      0.24             2.18             7.80  0.86   
4      0.39             1.82             4.32  1.04   

   OD280/OD315 of diluted wines  Proline  
0                          3.92     1065  
1                          3.40     1050  
2                          3.17     1185  
3                          3.45     1480  
4                          2.93      735

In [35]:
df.shape

(178, 14)

In [5]:
x= df.drop('Class', axis=1)
y= df.Class
x_std= StandardScaler().fit_transform(x)

In [83]:
x_train, x_test, y_train, y_test = train_test_split(x_std,y, test_size = 0.3, random_state=2)

In [7]:
model = GaussianNB()
model.fit(x_train,y_train)
ypred=model.predict(x_test)

In [8]:
print(metrics.accuracy_score(y_test,ypred),'\n\n')
print(metrics.confusion_matrix(y_test,ypred),'\n\n')
print(print(metrics.classification_report(y_test,ypred)))

0.9629629629629629 


[[19  1  0]
 [ 0 20  0]
 [ 0  1 13]] 


             precision    recall  f1-score   support

          1       1.00      0.95      0.97        20
          2       0.91      1.00      0.95        20
          3       1.00      0.93      0.96        14

avg / total       0.97      0.96      0.96        54

None


In [62]:
#dt_model= DecisionTreeClassifier(criterion='entropy', random_state=0)
#rf_model = RandomForestClassifier(criterion='entropy',random_state=0)
#log_model= LogisticRegression()
#NB_model = GaussianNB()
#knn_model = KNeighborsClassifier(weights= 'uniform', metric='euclidean')

In [63]:
params= {'max_depth': np.arange(1,30)}
GS= GridSearchCV(dt_model,params,cv=3)
GS.fit(x_std,y)
GS.best_params_

{'max_depth': 4}

In [77]:
params= {'n_neighbors': np.arange(1,30)}
GS= GridSearchCV(knn_model,params,cv=3)
GS.fit(x_std,y)
GS.best_params_

{'n_neighbors': 25}

In [65]:
params= {'max_depth': np.arange(1,30),'n_estimators': np.arange(1,60)}
GS= GridSearchCV(rf_model,params,cv=3)
GS.fit(x_std,y)
GS.best_params_

{'max_depth': 2, 'n_estimators': 40}

In [78]:
dt_model= DecisionTreeClassifier(criterion='entropy', max_depth=4, random_state=0)
rf_model = RandomForestClassifier(n_estimators=40, max_depth=2, random_state=0)
log_model= LogisticRegression()
NB_model = GaussianNB()
knn_model = KNeighborsClassifier(n_neighbors= 7, weights= 'uniform', metric='euclidean')

In [79]:
dt_model.fit(x_std,y)
rf_model.fit(x_std,y)
log_model.fit(x_std,y)
NB_model.fit(x_std,y)
knn_model.fit(x_std,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
           metric_params=None, n_jobs=1, n_neighbors=7, p=2,
           weights='uniform')

In [80]:
models=[]
models.append(('DecisionTree',dt_model))
models.append(('RandomForest',rf_model))
models.append(('LogisticReg', log_model))
models.append(('NaiveBayes', NB_model))
models.append(('KNeighbour',knn_model))
models

[('DecisionTree',
  DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, presort=False, random_state=0,
              splitter='best')),
 ('RandomForest',
  RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
              max_depth=2, max_features='auto', max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=40, n_jobs=1,
              oob_score=False, random_state=0, verbose=0, warm_start=False)),
 ('LogisticReg',
  LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
            intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
            pe

In [81]:
results= []
names= []
scoring= 'accuracy'

for name,model in models:
    kfold= model_selection.KFold(n_splits = 5, random_state=2)
    cv_results = model_selection.cross_val_score(model, x_std, y, cv=kfold, scoring=scoring)
    results.append(cv_results)
    names.append(name)
    msg = "%s: %f (%f)" %(name,cv_results.mean(),cv_results.std())
    print(msg)

DecisionTree: 0.881905 (0.048117)
RandomForest: 0.801905 (0.236152)
LogisticReg: 0.955397 (0.037611)
NaiveBayes: 0.932698 (0.028405)
KNeighbour: 0.904762 (0.062373)


In [93]:
pred_test= log_model.predict_proba(x_test)

pred_test[:,1]

y_test

12     1
23     1
166    3
25     1
35     1
13     1
65     2
171    3
112    2
48     1
78     2
3      1
6      1
158    3
149    3
122    2
42     1
2      1
29     1
157    3
130    3
45     1
106    2
94     2
5      1
53     1
93     2
41     1
54     1
24     1
133    3
64     2
151    3
153    3
28     1
113    2
154    3
120    2
89     2
92     2
156    3
144    3
79     2
14     1
163    3
119    2
129    2
44     1
150    3
66     2
123    2
127    2
109    2
85     2
Name: Class, dtype: int64