In [9]:
def function_d(d):
    print(d)
    return

def function_c(c):
    len1=len(c)
    a=0
    t=''
    temp=[]
    while(a<len1):
        if c[a].isdigit():
            temp.append(c[a])
            t=t+temp[a]
        a+=1
    temp3=[t]
    function_b(temp3)
   
            
    
    
def function_b(b):
    for i in b:
        if i.isdigit():
            function_d(i)
        elif i.isalpha():
            continue
        else:
            function_c(i)
    return
        
    
def  function_a(a):
    list1=a.split(" ")
    function_b(list1)
    return


b="She is in her 40's but behaves as if she is a teenager who is 16! 56 98lo"

function_a(b)

40
16
56
98


In [11]:
list1=[45,50,43,60,56,48,10,15,20,19,60,40,40,43,50,50,65,70,75,80,13,40,40,50]

countval= lambda a: list1.count(a)

list2=list(map(countval,list1))

temp=0
for i in range(len(list2)):
    if temp<list2[i]:
        temp=list2[i]
        indexnumber=i

temp=[]
for i in range(len(list2)):
    if list2[indexnumber]==list2[i]:
        temp.append(list1[i])
        
print("Mode of the list is : ", set(temp))  
    
temp

Mode of the list is :  {40, 50}


[50, 40, 40, 50, 50, 40, 40, 50]

In [3]:
list1.count(45)

1

In [4]:
max(list2)

3

In [12]:
list1=["String1","100","String2","200","String3"]

for item in list1:
    if not(item.isdigit()):
        continue
    print(item)

100
200


In [13]:
l=45.5


In [14]:
p=l.is_integer()

In [15]:
print(p)

False


In [16]:
x=100

def fun():
    x=200
    print(x)

fun()

print(x)

200
100


In [17]:
x=100

def fun():
    global x
    print(x)
    x=200

fun()

print(x)

100
200


In [11]:
version="Python"

def fun_update_version(val):
    global version
    version=version+" "+str(val)

fun_update_version(3.7)

print(version)

def print_version():
    global version
    print(version)

print_version()

Python 3.7
Python 3.7


In [12]:
l1=[1,2,3]
l2=[3,4,5]

l3=l1.append(l2)
print(l3)

None


In [13]:
a={4,2,3,5,7,8,1,6,1}
print(a)

{1, 2, 3, 4, 5, 6, 7, 8}


In [14]:
set1={1,2,3,4}
set2={4,5,6}

#to find intersetion

result= set1 & set2

print(result)

#to find union

result= set1 | set2

print(result)

#subtract

result3=set1-set2
print(result3)

result4=set2-set1
print(result4)

result5=(set1-set2)|(set2-set1)
print(result5)


{4}
{1, 2, 3, 4, 5, 6}
{1, 2, 3}
{5, 6}
{1, 2, 3, 5, 6}


In [15]:
type(set1)

set

In [16]:
list1=[1,2,3,4,1,2]
set1=set(list1)

print(set1)

{1, 2, 3, 4}


In [17]:
l1={"Ram","David","Raheem"}
l2={"Lakhan","Ram"}

result=l1 & l2

print(result)

{'Ram'}


In [18]:
import numpy

array1= numpy.array([1,2,3,4,5])

print(array1)

[1 2 3 4 5]


In [37]:
import numpy as np

array2=np.array([5,6,3])

print(array2)

[5 6 3]


In [26]:
list1=[1,2,3]
list2=[4,5,6]

list3=list1+list2

print(list3)

[1, 2, 3, 4, 5, 6]


In [27]:
list1=np.array([1,2,3])
list2=np.array([4,5,6])

list3=list1+list2

print(list3)

[5 7 9]


In [42]:
import numpy as np

mat1=np.array(([1,2,3],[4,5,6],[7,8,9]))

print(mat1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
mat1[2][1]

8

In [44]:
mat1=np.array(([1,2],[3,4]))
mat2=np.array(([5,6],[7,8]))

print(np.multiply(mat1,mat2))

[[ 5 12]
 [21 32]]


In [45]:
mat1=np.array(([1,2,3],[4,5,6],[7,8,9]))

print(mat1*5)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [47]:
mat1=np.array(([1,2],[3,4]))
mat2=np.array(([5,6],[7,8]))

print(np.matmul(mat1,mat2))

[[19 22]
 [43 50]]


In [48]:
import sys

a=10

sys.getsizeof(a)

28

In [49]:
list1=[1,2,3,4]

sys.getsizeof(list1)

96

In [55]:
list1=[1,2,3,4]

sys.getsizeof(list1[0])*len(list1)

112

In [56]:
list2=list(range(1000))

sys.getsizeof(list2)

9112

In [79]:
list2=list(range(100000))

sys.getsizeof(list2[0])*len(list2)

2400000

In [82]:
array1=np.arange(100000)

sys.getsizeof(array1[0])

28

In [77]:
array1.size

100000

In [83]:
array1.itemsize

4

In [75]:
list1=[]
sys.getsizeof(list1)

64

In [86]:
import time
start=time.time()
print(start)
list2=list(range(1000))



1542265217.95093


In [93]:
arr1=np.arange(1000)
print(arr1.shape)
arr2=arr1.reshape(10,10,10)
print(arr2.shape)

(1000,)
(10, 10, 10)


In [102]:
list1=[1,2,3,4,6]
itervar= iter(list1)

In [105]:
next(itervar)

1

In [106]:
next(itervar)

2

In [107]:
dict1={45:55,85:89}
dict1[45]

55

In [108]:
dict1.get(56,89)

89

In [109]:
dict1

{45: 55, 85: 89}

In [114]:
list1=[1,2,3,4]
list2=[4,5,6,7]
dict1={}

for i in range(len(list1)):
    dict1[list1[i]]=list2[i]

print(dict1)  

{1: 4, 2: 5, 3: 6, 4: 7}


In [116]:
arr1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

var=arr1.shape
row1=int(var[0])-1
row2=int(var[1])-1

print("The four values are: \n", arr1[0][0],"\n",arr1[0][row2],"\n",arr1[row1][0],"\n",arr1[row1][row2])

The four values are: 
 1 
 4 
 9 
 12


In [21]:
import numpy as np

sud=np.array([[2,0,1,0],[1,0,2,3],[4,1,0,2],[0,2,0,1]])

print("The input sudoku query is :\n\n",sud)

temp=sud.shape
length=temp[0]

def sudsol(sud):
    for i in range(length):
        for j in range(length):
            if sud[i][j]==0:
                temp1=1
                temp2=1
                count=[]
                for k in range(length):
                    if sud[i][k]!=0:
                        count.insert(0,(sud[i][k]))
                    if sud[k][j]!=0:
                        count.insert(0,(sud[k][j]))
                set1=set(count)
                set2={1,2,3,4}
                if len(set1)>=4:
                    print("Error in the row: ",i,"\n and the column: ",j)
                elif len(set1)==3:
                    set3=set2-set1
                    templist=list(set3)
                    sud[i][j]=templist[0]
                else:
                    continue
    return


sudsol(sud)

print("\nThe result of the above query is:\n\n",sud)



The input sudoku query is :

 [[2 0 1 0]
 [1 0 2 3]
 [4 1 0 2]
 [0 2 0 1]]

The result of the above query is:

 [[2 0 1 4]
 [1 4 2 3]
 [4 1 3 2]
 [3 2 4 1]]


In [16]:
for i in range(length):
    for j in range(length):
        if sud[i][j]==0:
            temp1=1
            temp2=1
            count=[]
            for k in range(length):
                if sud[i][k]!=0:
                    count.insert(0,(sud[i][k]))
                if sud[k][j]!=0:
                    count.insert(0,(sud[k][j]))
            set1=set(count)
            set2={1,2,3,4}
            if len(set1)==4:
                print("Error in the row: ",i,"\n and the column: ",j)
            elif len(set1)==3:
                set3=set2-set1
                templist=list(set3)
                sud[i][j]=templist[0]
            else:
                continue
                    
print("\nThe result of the above query is:\n\n",sud)


The result of the above query is:

 [[2 3 1 4]
 [1 4 2 3]
 [4 1 3 2]
 [3 2 4 1]]


In [1]:
l1=[1,2,3]

In [3]:
l1.clear()

In [4]:
l1

[]

NameError: name 'np' is not defined

In [1]:
t=''

In [5]:
t=t+'a'

In [6]:
t+'b'

'ab'