In [1]:
import numpy as np

arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [2]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
arr1.sum(0)

array([12, 15, 18])

In [4]:
arr2=np.arange(9)

In [5]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
arr2.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
arr1.sum(1)

array([ 6, 15, 24])

In [9]:
import pandas as pd

In [12]:
from pandas import Series, DataFrame

In [13]:
arr1=np.arange(1,10).reshape(3,3)

In [14]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr2=np.arange(11)

In [16]:
arr2[2:6]

array([2, 3, 4, 5])

In [17]:
arr1[1]

array([4, 5, 6])

In [25]:
arr1[:,0]

array([1, 4, 7])

In [28]:
arr1[1:,1:]

array([[5, 6],
       [8, 9]])

In [30]:
arr1[1:,:2]

array([[4, 5],
       [7, 8]])

In [31]:
arr1[:2,1:]

array([[2, 3],
       [5, 6]])

In [32]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
slice1=arr2[2:6]

In [35]:
slice1

array([2, 3, 4, 5])

In [36]:
slice1[:]=99

In [37]:
slice1

array([99, 99, 99, 99])

In [38]:
arr2

array([ 0,  1, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [42]:
slice2=arr2.copy()

In [44]:
slice2[:]=63

In [45]:
slice2

array([63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63])

In [46]:
arr2

array([ 0,  1, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [47]:
slice3=arr2[2:7].copy()

In [48]:
slice3

array([99, 99, 99, 99,  6])

In [49]:
slice3[:]=69

In [61]:
arr4=np.zeros((10,10))

In [62]:
arr4

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [90]:
for i in range(10):
    arr4[i]=i

In [91]:
arr4

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [92]:
arr4.T

array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [93]:
np.dot(arr4,arr4.T)

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90.],
       [  0.,  20.,  40.,  60.,  80., 100., 120., 140., 160., 180.],
       [  0.,  30.,  60.,  90., 120., 150., 180., 210., 240., 270.],
       [  0.,  40.,  80., 120., 160., 200., 240., 280., 320., 360.],
       [  0.,  50., 100., 150., 200., 250., 300., 350., 400., 450.],
       [  0.,  60., 120., 180., 240., 300., 360., 420., 480., 540.],
       [  0.,  70., 140., 210., 280., 350., 420., 490., 560., 630.],
       [  0.,  80., 160., 240., 320., 400., 480., 560., 640., 720.],
       [  0.,  90., 180., 270., 360., 450., 540., 630., 720., 810.]])

In [94]:
arr4[[2,4,6]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.]])

In [97]:
arr4[[3,5,2]]

array([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]])

In [101]:
arr5=np.arange(18)

In [106]:
arr5.reshape(3,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [107]:
from numpy.random import randn

In [108]:
arr5=randn(6)

In [109]:
arr5

array([ 1.13646035, -0.14957145, -0.09737047, -0.85153442, -0.64053579,
       -0.02088947])

In [110]:
from numpy.random import randint

In [111]:
arr6=randint(6)

In [112]:
arr6

2

In [116]:
arr6=randint(1,51,5)

In [114]:
arr6

array([15, 46,  6, 39, 50])

In [117]:
c=np.array([True,False,True])

In [118]:
c

array([ True, False,  True])

In [119]:
a=np.array([1,2,3])

In [121]:
b=np.array([10,20,30])

In [122]:
np.where(c,a,b)

array([ 1, 20,  3])

In [127]:
a=np.array([1,2,3,4]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [128]:
b=np.array([10,20,30,40]).reshape(2,2)
b

array([[10, 20],
       [30, 40]])

In [129]:
c=np.array([True,False,True,False]).reshape(2,2)
c

array([[ True, False],
       [ True, False]])

In [130]:
np.where(c,b,a)

array([[10,  2],
       [30,  4]])

In [132]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [133]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [138]:
np.where(arr1<6)

(array([0, 0, 0, 1, 1], dtype=int64), array([0, 1, 2, 0, 1], dtype=int64))

In [135]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [139]:
list1=["Banglore","Chennai","Mumbai","Pune","Banglore"]

In [140]:
arr1=np.array(list1)

In [141]:
arr1

array(['Banglore', 'Chennai', 'Mumbai', 'Pune', 'Banglore'], dtype='<U8')

In [142]:
arr2=np.unique(arr1)

In [143]:
arr2

array(['Banglore', 'Chennai', 'Mumbai', 'Pune'], dtype='<U8')

In [151]:
arr1=np.arange(10,51,10)

In [152]:
arr1

array([10, 20, 30, 40, 50])

In [146]:
np.save("myarray",arr1)

In [147]:
arr2=np.load("myarray.npy")

In [148]:
arr2

array([1, 2, 3, 4])

In [153]:
np.savetxt("myarraytxt.txt",arr1)

In [150]:
pwd

'C:\\Users\\Gaurav'

In [154]:
arr2=np.array([5,3,6,0.6,10])


In [155]:
np.savetxt("myarraynew.txt",arr2)

In [156]:
a=np.array([True,False,True])

In [157]:
a.any()

True

In [158]:
a.all()

False

In [159]:
b=np.array([False,False,False])

In [160]:
b.any()

False

In [161]:
b.all()

False

In [170]:
a=np.array([1,2,np.nan])

In [171]:
a

array([ 1.,  2., nan])

In [165]:
c=a+b

In [169]:
b=np.array([1,2,3])
a

array([ 1.,  2., nan])

In [172]:
c=a+b

In [173]:
c

array([ 2.,  4., nan])

In [180]:
np.isnan(c)

array([False, False,  True])

In [183]:
np.isnat(c)

TypeError: ufunc 'isnat' is only defined for datetime and timedelta.

In [186]:
from pandas import Series,DataFrame
ser1=Series([1,2,3])

In [187]:
ser1

0    1
1    2
2    3
dtype: int64

In [190]:
ser2=Series(["a","b","c"])
ser2

0    a
1    b
2    c
dtype: object

In [195]:
ser3=Series(["a","b","c"],[1,2,3])

In [196]:
ser3

1    a
2    b
3    c
dtype: object

In [197]:
ser4=Series([1,2,3],index=["a","b","c"])

In [198]:
ser4

a    1
b    2
c    3
dtype: int64

In [200]:
ser4["a"]

1

In [203]:
ser4=Series({"a":1,"b":2,"c":3})

In [204]:
ser4

a    1
b    2
c    3
dtype: int64

In [212]:
ser5=Series(["Nagpur","Bangalore","Pune"],index=["a","b","c"])

In [213]:
ser5

a       Nagpur
b    Bangalore
c         Pune
dtype: object

In [216]:
ser5.values

array(['Nagpur', 'Bangalore', 'Pune'], dtype=object)

In [217]:
ser5[0]

'Nagpur'

# Selecting Entries

In [218]:
ser5[0] #grab by index

'Nagpur'

In [220]:
ser4

a    1
b    2
c    3
dtype: int64

In [223]:
ser4[ser4<=2] #grab by logic

a    1
b    2
dtype: int64

In [224]:
ser3

1    a
2    b
3    c
dtype: object

In [226]:
dict(ser4)

{'a': 1, 'b': 2, 'c': 3}

In [228]:
ser4.to_dict()

{'a': 1, 'b': 2, 'c': 3}

In [233]:
list1=["a","b","c","d"]

In [231]:
ser4

a    1
b    2
c    3
dtype: int64

In [243]:
dict1=ser4.to_dict()

In [244]:
dict1

{'a': 1, 'b': 2, 'c': 3}

In [245]:
s1=Series(dict1,index=list1)

In [246]:
s1

a    1.0
b    2.0
c    3.0
d    NaN
dtype: float64

In [239]:
s1["d"]=4

In [247]:
s1

a    1.0
b    2.0
c    3.0
d    NaN
dtype: float64

In [249]:
s1.isnull().sum()

1

In [250]:
s1.notnull().sum()

3

In [251]:
s1

a    1.0
b    2.0
c    3.0
d    NaN
dtype: float64

In [254]:
s1.name="None Value function"

In [255]:
s1

a    1.0
b    2.0
c    3.0
d    NaN
Name: None Value function, dtype: float64

In [256]:
s1.index.name="Alphabets"

In [257]:
s1

Alphabets
a    1.0
b    2.0
c    3.0
d    NaN
Name: None Value function, dtype: float64

In [260]:
s1.label="Number"

In [261]:
s1

Alphabets
a    1.0
b    2.0
c    3.0
d    NaN
Name: None Value function, dtype: float64

In [262]:
s1+4

Alphabets
a    5.0
b    6.0
c    7.0
d    NaN
Name: None Value function, dtype: float64

In [264]:
s1*89

Alphabets
a     89.0
b    178.0
c    267.0
d      NaN
Name: None Value function, dtype: float64

In [276]:
dframe1=DataFrame(np.arange(9).reshape(3,3),index=["a","b","c"], columns=["Col1","Col2","Col3"])

In [277]:
dframe1

Col1  Col2  Col3
a     0     1     2
b     3     4     5
c     6     7     8

In [278]:
dframe1

Col1  Col2  Col3
a     0     1     2
b     3     4     5
c     6     7     8

In [279]:
dframe2=DataFrame({"Aplha":["One","Two","Three"],"Num": [1,2,3]}, index=["a","b","c"])
dframe2

Aplha  Num
a    One    1
b    Two    2
c  Three    3

In [280]:
dict1={"Company":["facebook","Google","Microsoft"],"Price":[1000,2000,3000],"Ticker":["FB","GOOG","MIC"]}

In [283]:
dframe3=DataFrame(dict1,index=[1,2,3])

In [284]:
dframe3

Company  Price Ticker
1   facebook   1000     FB
2     Google   2000   GOOG
3  Microsoft   3000    MIC

In [285]:
dframe3["Company"]

1     facebook
2       Google
3    Microsoft
Name: Company, dtype: object

In [286]:
dframe3["Price"].sum()

6000

In [303]:
dframe3.ix[2]

C:\Users\Gaurav\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


Company    Google
Price        2000
Ticker       GOOG
Name: 2, dtype: object

In [300]:
dframe3.iloc[1]

Company    Google
Price        2000
Ticker       GOOG
Name: 2, dtype: object

In [302]:
dframe3.loc[3]

Company    Microsoft
Price           3000
Ticker           MIC
Name: 3, dtype: object

In [304]:
dict1

{'Company': ['facebook', 'Google', 'Microsoft'],
 'Price': [1000, 2000, 3000],
 'Ticker': ['FB', 'GOOG', 'MIC']}

In [307]:
dframe1.loc["a"]

Col1    0
Col2    1
Col3    2
Name: a, dtype: int32

In [308]:
dframe3

Company  Price Ticker
1   facebook   1000     FB
2     Google   2000   GOOG
3  Microsoft   3000    MIC

In [312]:
dframe3["DPrice"]=[500,1000,1500]

In [313]:
dframe3

Company  Price Ticker  DPrice
1   facebook   1000     FB     500
2     Google   2000   GOOG    1000
3  Microsoft   3000    MIC    1500

In [315]:
dframe3["x"]="a"

In [316]:
dframe3

Company  Price Ticker  DPrice  x
1   facebook   1000     FB     500  a
2     Google   2000   GOOG    1000  a
3  Microsoft   3000    MIC    1500  a

In [320]:
dframe3["DiscPrice"]= dframe3["Price"] *0.10

In [321]:
dframe3

Company  Price Ticker  DPrice  x  DiscPrice
1   facebook   1000     FB     500  a      100.0
2     Google   2000   GOOG    1000  a      200.0
3  Microsoft   3000    MIC    1500  a      300.0

In [323]:
del dframe3["x"]

In [325]:
del dframe3["DPrice"]

In [326]:
dframe3

Company  Price Ticker  DiscPrice
1   facebook   1000     FB      100.0
2     Google   2000   GOOG      200.0
3  Microsoft   3000    MIC      300.0

In [328]:
del dframe3.iloc[1]

AttributeError: __delitem__

In [335]:
dframe3.drop(1,inplace=True)

In [360]:
dframe3

Company  Price Ticker  DiscPrice
2  Microsoft   3000    MIC      300.0
3  Microsoft   3000    MIC      300.0
4  Microsoft   3000    MIC      300.0
1   Facebook   1000     FB      100.0

In [348]:
dframe3.iloc[1]=["Facebook",1000,"FB",100.0]

In [355]:
dframe3.loc[4]=["Microsoft",3000,"MIC",300.0]

In [359]:
dframe3.loc[1]=["Facebook",1000,"FB",100.0]

In [357]:
ser1=Series({0:"India",5:"Pakistan",10:"Bangladesh"})

In [358]:
ser1

0          India
5       Pakistan
10    Bangladesh
dtype: object

In [364]:
ser1.reindex(np.arange(15),method='ffill')

0          India
1          India
2          India
3          India
4          India
5       Pakistan
6       Pakistan
7       Pakistan
8       Pakistan
9       Pakistan
10    Bangladesh
11    Bangladesh
12    Bangladesh
13    Bangladesh
14    Bangladesh
dtype: object

In [362]:
ser2=Series(["India","Pakistan","Bangladesh"], index=[0,5,15])

In [365]:
ser2

0          India
5       Pakistan
15    Bangladesh
dtype: object

In [366]:
ser2.reindex(np.arange(15),method='bfill')

0          India
1       Pakistan
2       Pakistan
3       Pakistan
4       Pakistan
5       Pakistan
6     Bangladesh
7     Bangladesh
8     Bangladesh
9     Bangladesh
10    Bangladesh
11    Bangladesh
12    Bangladesh
13    Bangladesh
14    Bangladesh
dtype: object

In [368]:
dframe3

Company  Price Ticker  DiscPrice
2  Microsoft   3000    MIC      300.0
3  Microsoft   3000    MIC      300.0
4  Microsoft   3000    MIC      300.0
1   Facebook   1000     FB      100.0

In [369]:
ser5=Series([1,2,3],index=["B","C","D"])

In [370]:
ser5

B    1
C    2
D    3
dtype: int64

In [384]:
reindexser=ser5.reindex(["A","B","C","D","E"],fill_value=0)
reindexser

A    0
B    1
C    2
D    3
E    0
dtype: int64