# Numpy

In [1]:
import numpy as np

In [2]:
tu=(1,2,3)

In [5]:
type(tu)

out_tu= np.array(tu)

print(out_tu)

[1 2 3]


In [4]:
type(out_tu)

numpy.ndarray

In [6]:
l1=[1,2,3,4,5,6]

out_l1=np.array(l1)

In [8]:
out_l1.shape

(6,)

In [9]:
out_l1.ndim

1

In [34]:
arr=np.array([[1,2,3],[1,2,3]])

In [11]:
arr.ndim

2

In [12]:
arr

array([[1, 2, 3],
       [1, 2, 3]])

In [13]:
arr.size

6

In [15]:
print(arr.size)
print(arr.shape)
print(arr.ndim)
print(arr.itemsize)
print(arr.nbytes)
print(len(arr))

6
(2, 3)
2
4
24
2


In [25]:
arr1=np.array([1,2,3,6,4])
int1=arr1.astype(int)

In [24]:
arr1

array([1, 2, 3, 6, 4])

In [26]:
int1

array([1, 2, 3, 6, 4])

In [27]:
type(int1)

numpy.ndarray

In [29]:
np.linspace(1,5,num=4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [30]:
np.linspace(1,50,100)

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

In [31]:
celcius=[2,5.6,85,2.8]

arr=np.array(celcius)

In [32]:
print(arr*9/6+32)

[ 35.   40.4 159.5  36.2]


In [35]:
print(arr)

[[1 2 3]
 [1 2 3]]


In [36]:
aronce=np.ones([3,3])

In [37]:
print(aronce)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [46]:
arran=np.random.random([2,3])

In [47]:
print(arran)

[[0.43141794 0.89528047 0.38333683]
 [0.53711686 0.92951811 0.71595091]]


In [54]:
arr=np.array([[[1,2],[1,3]],[[2,6],[5,6]]])

In [55]:
print(arr)

[[[1 2]
  [1 3]]

 [[2 6]
  [5 6]]]


In [59]:
arrn=np.array([1,2,3,4,5], ndmin=3)

In [61]:
print(arrn)

print(arrn.shape)

[[[1 2 3 4 5]]]
(1, 1, 5)


In [68]:
list1=[1,2,3,6,5,4]
i16=np.dtype(np.int)

a=np.array(list1,dtype=i16)
print (a)

print(a.itemsize)
print(a.nbytes)

[1 2 3 6 5 4]
4
24


In [93]:
student=np.dtype([('name','S5'),('age','i'),('marks','i')])

a=np.array([('abc',12,96),('Deabasis',15,33)], dtype=student)

print(a)
print(a.shape)
print(a['name'])
print(a['marks'])

[(b'abc', 12, 96) (b'Deaba', 15, 33)]
(2,)
[b'abc' b'Deaba']
[96 33]


In [96]:
print(a[1])

(b'Deaba', 15, 33)


In [109]:
employee=np.dtype([('Eid','i'),('Ename','S10'),('Salary','f')])

a=np.array([(102,'Ambarish',9600),(105,'Praveen',33000)], dtype=employee)

print(a)
print(a.shape)
print(a['Ename'])
print(a['Salary'])

[(102, b'Ambarish',  9600.) (105, b'Praveen', 33000.)]
(2,)
[b'Ambarish' b'Praveen']
[ 9600. 33000.]


In [114]:
dt=np.dtype([('time',[('hr',int),('min',int),('sec',int)]),('temp',float)])
dt

time_temp=np.array([[((11,12,13),23.8),((12,1,25),36.8),((6,35,25),56.8)]],dtype=dt)

print(time_temp[:])
print(time_temp['time']['min'])

[[((11, 12, 13), 23.8) ((12,  1, 25), 36.8) (( 6, 35, 25), 56.8)]]
[[12  1 35]]


In [129]:
x=np.arange(16)

x=x.reshape(4,4)

a=x[:2,:3]

print(x)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2]
 [4 5 6]]


In [137]:
b=np.hsplit(x,2)
c=np.vsplit(b[0],2)
d=np.vsplit(b[1],2)
print(c[0],"\n\n",c[1],"\n\n",d[0],"\n\n",d[1])

[[0 1]
 [4 5]] 

 [[ 8  9]
 [12 13]] 

 [[2 3]
 [6 7]] 

 [[10 11]
 [14 15]]


In [138]:
add= lambda x,y:x+y



In [139]:
add(2,6)

8

In [140]:
cube=lambda x:x*x*x

cube(3)

27

In [141]:
def myfunc(n):
    return lambda a:a*n

mytripler=myfunc(3)

mytripler(5)

15

In [146]:


l1=[2,65,3,25,55,65,32,86,21,22]

final_list = list(filter(lambda x: (x%2==0),l1))

print(final_list)

[2, 32, 86, 22]


In [152]:
dict1=[{'name':'python','point':10},{'name':'java','point':15}]

In [165]:
import functools
p=functools.reduce(lambda x,y:x+y,l1)
p

376

In [167]:
import itertools
q=list(itertools.accumulate(l1,(lambda x,y :x+y)))
q

[2, 67, 70, 95, 150, 215, 247, 333, 354, 376]