In [1]:
import numpy as np

In [2]:
sud=np.array([[0,4,0,0],[3,0,4,0],[1,0,0,4],[0,2,1,0]])

In [3]:
print(sud)

[[0 4 0 0]
 [3 0 4 0]
 [1 0 0 4]
 [0 2 1 0]]


In [4]:
temp=sud.shape
length=temp[0]

In [6]:
for i in range(length):
    for j in range(length):
        if sud[i][j]==0:
            temp1=1
            temp2=1
            count=[]
            for k in range(length):
                for l in range (length):
                    if sud[i][k]==l+1:
                        count.insert(0,(sud[i][k]))
                        temp1+=1
                    if sud[k][j]==l+1:
                        count.insert(0,(sud[k][j]))
                        temp2+=1
            set1=set(count)
            set2={1,2,3,4}
            if len(set1)==4:
                print("Error in the row: ",i,"\n and the column: ",j)
            elif len(set1)==3:
                set3=set2-set1
                templist=list(set3)
                sud[i][j]=templist[0]
            else:
                continue
                    

In [28]:
list1=[1,2,3]
list1.insert(0,5)

In [7]:
print(sud)

[[2 4 3 1]
 [3 1 4 2]
 [1 3 2 4]
 [4 2 1 3]]


In [44]:
sud[0][0]=5

In [33]:
sud.size


16

In [53]:
list1=[1,3,2,4,2,3,3,5]
set2={5,3}
set1=set(list1)
print(set1)

{1, 2, 3, 4, 5}


In [58]:
type(len(set1))

int

In [72]:
set1={1,2,3}
set2={1,2,3,4}

set3=set2-set1

In [66]:
set3

{4}

In [67]:
type(set3)

set

In [75]:
l2=list(set3)

In [69]:
l2

[4]

In [76]:
l2[0]

4

In [105]:
import numpy as np

sud=np.array([[2,0,0,3,0,0,0,0,0],[8,0,4,0,6,2,0,0,3],[0,1,3,8,0,0,2,0,0],[0,0,0,0,2,0,3,9,0],[5,0,7,0,0,0,6,2,1],[0,3,2,0,0,6,0,0,0],[0,2,0,0,0,9,1,4,0],[6,0,1,2,5,0,8,0,9],[0,0,0,0,0,1,0,0,2]])


print("The input sudoku query is :\n\n",sud)

temp=sud.shape
length=temp[0]


for i in range(length):
    for j in range(length):
        if sud[i][j]==0:
            temp1=1
            temp2=1
            count=[]
            for k in range(length):
                for l in range (length):
                    if sud[i][k]==l+1:
                        count.insert(0,(sud[i][k]))
                        temp1+=1
                    if sud[k][j]==l+1:
                        count.insert(0,(sud[k][j]))
                        temp2+=1
            set1=set(count)
            set2={1,2,3,4,5,6,7,8,9}
            if len(set1)==9:
                print("Error in the row: ",i,"\n and the column: ",j)
            elif len(set1)==8:
                set3=set2-set1
                templist=list(set3)
                sud[i][j]=templist[0]
            else:
                continue
                    
print("\nThe result of the above query is:\n\n",sud)

The input sudoku query is :

 [[2 0 0 3 0 0 0 0 0]
 [8 0 4 0 6 2 0 0 3]
 [0 1 3 8 0 0 2 0 0]
 [0 0 0 0 2 0 3 9 0]
 [5 0 7 0 0 0 6 2 1]
 [0 3 2 0 0 6 0 0 0]
 [0 2 0 0 0 9 1 4 0]
 [6 0 1 2 5 0 8 0 9]
 [0 0 0 0 0 1 0 0 2]]

The result of the above query is:

 [[2 0 0 3 0 0 0 0 0]
 [8 0 4 0 6 2 0 0 3]
 [0 1 3 8 0 0 2 0 0]
 [0 0 0 0 2 0 3 9 0]
 [5 0 7 0 0 0 6 2 1]
 [0 3 2 0 0 6 0 0 0]
 [0 2 0 0 0 9 1 4 0]
 [6 0 1 2 5 0 8 0 9]
 [0 0 0 0 0 1 0 0 2]]


In [116]:
for i in range(length):
    for j in range(length):
        if sud[i][j]==0:
            temp1=1
            temp2=1
            count=[]
            for k in range(length):
                for l in range (length):
                    if sud[i][k]==l+1:
                        count.insert(0,(sud[i][k]))
                        temp1+=1
                    if sud[k][j]==l+1:
                        count.insert(0,(sud[k][j]))
                        temp2+=1
            set1=set(count)
            set2={1,2,3,4,5,6,7,8,9}
            if len(set1)==9:
                continue
            elif len(set1)==8:
                set3=set2-set1
                templist=list(set3)
                sud[i][j]=templist[0]
            else:
                continue

print("\nThe result of the above query is:\n\n",sud)


The result of the above query is:

 [[2 0 5 3 8 7 9 1 4]
 [8 9 4 1 6 2 7 5 3]
 [0 1 3 8 7 5 2 0 6]
 [7 6 0 4 2 8 3 9 5]
 [5 8 7 9 3 4 6 2 1]
 [1 3 2 7 4 6 5 0 8]
 [0 2 8 6 0 9 1 4 7]
 [6 4 1 2 5 3 8 7 9]
 [3 7 6 5 9 1 4 8 2]]


In [119]:
var=int(input())
sum1=0
a=0
while(True):
    sum1=sum1+a
    if a==var:
        break
    a+=1
print("The sum of the program is : ",sum1)

10
The sum of the program is :  55


In [20]:
import numpy as np

sud=np.array([[2,0,1,0],[1,0,0,3],[4,1,0,2],[0,2,0,1]])

print("The input sudoku query is :\n\n",sud)

temp=sud.shape
length=temp[0]

def funcsudsol(sud):
    for i in range(length):
        for j in range(length):
            if sud[i][j]==0:
                count=[]
                for k in range(length):
                    if sud[i][k]!=0:
                        count.insert(0,(sud[i][k]))
                    if sud[k][j]!=0:
                        count.insert(0,(sud[k][j]))
                set1=set(count)
                set2={1,2,3,4}
                if len(set1)==4:
                    print("Error in the row: ",i,"\n and the column: ",j)
                elif len(set1)==3:
                    set3=set2-set1
                    templist=list(set3)
                    sud[i][j]=templist[0]
                else:
                    continue
    return
  
for i in range(length):
    for j in range(length):
        if sud[i][j]==0:
            funcsudsol(sud)
        i=0
        j=0
                    
print("\nThe result of the above query is:\n\n",sud)

The input sudoku query is :

 [[2 0 1 0]
 [1 0 0 3]
 [4 1 0 2]
 [0 2 0 1]]

The result of the above query is:

 [[2 3 1 4]
 [1 4 2 3]
 [4 1 3 2]
 [3 2 4 1]]


In [13]:
sud=np.array([[2,0,1,0],[1,0,2,3],[4,1,0,2],[0,2,0,1]])
print(sud)

[[2 0 1 0]
 [1 0 2 3]
 [4 1 0 2]
 [0 2 0 1]]


In [15]:
t= sud[2,1]

In [16]:
type(t)

numpy.int32

In [17]:
list1=[]

In [18]:
list1.append(sud[2,1])

In [19]:
list1

[1]